wsdl: 'https://account.ymcamn.org/SSO/webservice/service.asmx?wsdl'
vendor_id: 8
vendor_username: ClockWork
vendor_password: ***REMOVED***
vendor_block: ***REMOVED***
url_login: 'https://account.ymcamn.org/PersonifyEBusiness/Default.aspx?TabID=337'
url_account: 'https://account.ymcamn.org/PersonifyEbusiness/MyY/tabid/61/Default.aspx'
url_sign_out: 'https://account.ymcamn.org/PersonifyEbusiness/MyY/tabid/61/ctl/Logoff/Default.aspx'
url_cart: 'https://account.ymcamn.org/PersonifyEbusiness/YMCA/ShoppingCart.aspx'
customer_orders_endpoint: 'http://ylayer.personifycloud.com/personifydataservices/personifydata.svc/CL_MindBodyCustomerOrder'
customer_orders_username: FFWUSER
customer_orders_password: ***REMOVED***
